en:
  languageCode: en
  languageName: English
  title: Boz's Blog
  menu:
    main:
      - identifier: archives
        name: Archive
        pageRef: archives
        weight: 5

      - identifier: search
        name: Search
        pageRef: search
        weight: 10

      - identifier: tags
        name: Tags
        pageRef: tags
        weight: 15

      - identifier: about
        name: About
        pageRef: about
        weight: 20

  params:
      description: "Boz's Blog, sharing my journey."
      homeInfoParams:
        Title: "Boz's Blog"
        subtitle: "Notes, technical writing, and thoughts."
        Content: >
          👋  Welcome to boz's Blog!
zh:
  languageCode: zh-CN
  languageName: 中文
  title: Boz's博客
  menu:
    main:
      - identifier: thoughts
        name: Thoughts
        pageRef: thoughts
        weight: 10

      - identifier: search
        name: Search
        pageRef: search
        weight: 20

      - identifier: tags
        name: Tags
        pageRef: tags
        weight: 30

      - identifier: archives
        name: Archive
        pageRef: archives
        weight: 40

      - identifier: about
        name: About
        pageRef: about
        weight: 50
  params:
    description: "Boz's 博客，分享我的技术写作。"
    homeInfoParams:
      Title: "Boz's 博客"
      Content: >
        👋 欢迎来到Boz's 博客！