[build.environment]
HUGO_VERSION = "0.152.2" # 改成和你本地的 hugo version 一致
TZ = "Asia/Shanghai"     # 可选，按自己时区改

[build]
publish = "public"             # 构建产物目录，默认就是 public
command = "hugo --gc --minify"
